### ISSUE TITLE
templateUrl not works

### ISSUE THREAD

**Issue by aakumykov** [driftyco/ionic2-module-template#12] opened 2017-08-18 05:52 UTC
Now it is impossible to use templateUrl in component inside module. Ionic project that uses such module cannot find html file with template. "npm run build" generates output tree with no *.html files.

Reproduce:

1) change "template" statement to "templateUrl: 'my-component.html'";
2) create my-component.html file in same folder with my-component.ts;
3) add "@@@" text to my-component.html (to find it later);
4) invoke "npm run build" in project folder;
5) invoke "tree dist" command in project folder to see no *.html files in this dir;
6) invoke "grep @@@ dist/" and see there is no content of template in dist dir at all.

OS: Debian Jessie amd64
NPM: 5.3.0
Node: 7.10.0
Ionic: 3.9.2

**Comment by mlynch** [comment] 2017-10-24 04:17
Dupe of #8

**Closed as completed by mlynch** 2017-10-24 04:17 UTC
